## Вычисления с помощью Numpy

 Задание 1

Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [2]:
import numpy as np 

In [3]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = np.mean(a,axis=0)
mean_a

array([2. , 8.4])

In [5]:
mean_a.shape

(2,)

Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [6]:
a_centered = a - mean_a.reshape((1,2))

In [7]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [8]:
a_centered_sp = np.dot(a_centered.T[0], a_centered.T[1])
a_centered_sp

8.0

In [9]:
a_centered_sp/(a_centered.shape[0]-1)

2.0

Задание 4

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [10]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

In [11]:
np.cov(a.T)[0,1]

2.0

## Работа с данными в Pandas

Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].

In [12]:
import pandas as pd

In [13]:
data = {'author_id':[1,2,3],'author_name':['Тургенеев','Чехов','Островский' ]}

In [14]:
authors = pd.DataFrame(data = data)
authors

author_id author_name
0          1   Тургенеев
1          2       Чехов
2          3  Островский

In [15]:
authors = pd.DataFrame(np.array([[1,'Тургенеев'],[2,'Чехов'],[3,'Островский']]), columns = ['author_id','author_name'])
authors

author_id author_name
0         1   Тургенеев
1         2       Чехов
2         3  Островский

In [16]:
entries = {
    'author_id': [1, 1, 1, 2, 2, 3, 3],
    'book_title': [
        'Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий',
        'Дама с собачкой', 'Гроза', 'Таланты и поклонники'
    ],
    'price':[450, 300, 350, 500, 450, 370, 290]
}

In [17]:
book = pd.DataFrame(data = entries)
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

Задание 2

 датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [18]:
book['author_id'] = book['author_id'].astype(int)
authors['author_id'] = authors['author_id'].astype(int)

authors_price = pd.merge(left=authors, right=book, left_on = 'author_id', right_on = 'author_id')
authors_price

author_id author_name            book_title  price
0          1   Тургенеев           Отцы и дети    450
1          1   Тургенеев                 Рудин    300
2          1   Тургенеев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [23]:
authors_stat = authors_price.groupby('author_name').agg({'price':[('min_price','min'),('max_price','max'),('mean_price','mean')]}) 

In [24]:
authors_price.groupby('author_name').agg(
    {'price': [('min_price', 'min'), ('max_price', 'max'), ('mean_price', 'mean')]})


price                      
            min_price max_price  mean_price
author_name                                
Островский        290       370  330.000000
Тургенеев         300       450  366.666667
Чехов             450       500  475.000000

Задание 3

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [19]:
top5 = authors_price.nlargest(5,'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1   Тургенеев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1   Тургенеев  Дворянское гнездо    350

Задание 4

Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.


In [20]:
d = {'author_name':authors_price['author_name'],'min_price':authors_price['price'].min(),'max_price':authors_price['price'].max(),'mean_price':authors_price['price'].mean()}

In [22]:
authors_stat

price                      
            min_price max_price  mean_price
author_name                                
Островский        290       370  330.000000
Тургенеев         300       450  366.666667
Чехов             450       500  475.000000

In [20]:
authors_stat = pd.DataFrame(d)
authors_stat

author_name  min_price  max_price  mean_price
0   Тургенеев        290        500  387.142857
1   Тургенеев        290        500  387.142857
2   Тургенеев        290        500  387.142857
3       Чехов        290        500  387.142857
4       Чехов        290        500  387.142857
5  Островский        290        500  387.142857
6  Островский        290        500  387.142857

Задание 5

Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.


In [21]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [22]:
authors_price

author_id author_name            book_title  price    cover
0          1   Тургенеев           Отцы и дети    450  твердая
1          1   Тургенеев                 Рудин    300   мягкая
2          1   Тургенеев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [24]:
import numpy as np

In [25]:
book_info = pd.pivot_table(authors_price,values='price',index = 'author_name',columns=['cover'], aggfunc = np.sum,fill_value=0)

In [26]:
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенеев       650      450
Чехов             0      950

In [27]:
book_info.to_pickle('./book_info.pkl')

In [28]:
book_info2 = pd.read_pickle('./book_info.pkl')

In [29]:
book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенеев       650      450
Чехов             0      950